### ISSUE TITLE
Unexpected value on the stack

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#1477] opened 2022-09-12 15:14 UTC
# Build commands
I compile the code with commit id 75936680662ddc31af6763daa55a622422f9e2f5.
Platform: Ubuntu 20.04
CPU: amd64 
compile:
```shell
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Debug -DWAMR_BUILD_FAST_INTERP=0 -Bbuild
cd build
make -j40
```
execute:
```shell
iwasm --heap-size=0 -f _start cp907_b4.wasm
```
[cp907_b4.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/9549360/cp907_b4.zip)

# Expected behavior:
The value left on the stack is 04 38 b3 7f

# Actual behavior:
The value left on the stack is 04 38 f3 7f

Maybe this unexpected behavior has a similar root cause to issue #1476.
Thank you.

**Comment by wenyongh** [comment] 2022-09-13 09:31
@erxiaozhou I tested in Ubuntu 20.04, x86-64, and cannot reproduce the issue. Could you please try modifying `fabs` below into `fabsf` in core/iwasm/interpreter/wasm_interpre_classic.c, and try again:
```
            HANDLE_OP(WASM_OP_F32_ABS)
            {
                DEF_OP_MATH(float32, F32, fabs);
                HANDLE_OP_END();
            }
```

**Comment by erxiaozhou** [comment] 2022-09-13 10:18
> @erxiaozhou I tested in Ubuntu 20.04, x86-64, and cannot reproduce the issue. Could you please try modifying `fabs` below into `fabsf` in core/iwasm/interpreter/wasm_interpre_classic.c, and try again:
> 
> ```
>             HANDLE_OP(WASM_OP_F32_ABS)
>             {
>                 DEF_OP_MATH(float32, F32, fabs);
>                 HANDLE_OP_END();
>             }
> ```

Thank you for your reply, modifying fabs to fabsf can fix this unexpected value.
Before fixing it, the value on frame_sp is
![before_fix](https://user-images.githubusercontent.com/32102519/189876412-578963d8-46f1-4cd3-88e5-1851369ba108.png)
After modifying fabs to fabsf, the value on frame_sp is as expected.

![after_fix](https://user-images.githubusercontent.com/32102519/189876772-e5f464c8-e1aa-4029-aee6-f757d961bdec.png)

**Comment by wenyongh** [comment] 2022-09-13 12:33
OK, I changed it to fabsf, and also applied similar changes to some other f32 operations, like ceilf, floorf, truncf, see #1480.

**Comment by wenyongh** [comment] 2022-09-22 05:18
Close this issue as it was fixed.

**Closed by wenyongh** 2022-09-22 05:18 UTC
