### ISSUE TITLE
LLVM ERROR: IMAGE_REL_AMD64_ADDR32NB relocation requires an ordered section layout

### ISSUE THREAD

**Issue by abc767234318** [bytecodealliance/wasm-micro-runtime#1348] opened 2022-08-01 13:41 UTC
I execute the following files in JIT mode.
[demo.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/9234339/demo.zip)
It prints the following error.
```
Exception: lookup the entry point symbol (like _start, main, _main, __main_argc_argv) failed
LLVM ERROR: IMAGE_REL_AMD64_ADDR32NB relocation requires an ordered section layout
```
However, no LLVM errors are printed in wasmtime and wasmer. I wonder if this is WAMR's problem.

**Comment by wenyongh** [comment] 2022-08-04 10:28
Hi, we have a test, but cannot reproduce the issue, wondering which JIT mode is used, and which platform, which arch?

**Comment by abc767234318** [comment] 2022-08-08 02:17
JIT mode: LLVM JIT
Platform: Windows 11
Arch: x86
@wenyongh

**Comment by wenyongh** [comment] 2022-08-10 06:36
@abc767234318 Thanks for reporting the issue, I submitted PR #1372 to fix it, please try again.

**Comment by wenyongh** [comment] 2022-09-22 05:19
Close this issue as it was fixed.

**Closed by wenyongh** 2022-09-22 05:19 UTC
